### ISSUE TITLE
Does it still work?

### ISSUE THREAD

**Issue by ElCoyote27** [JulienPalard/Allocine-PY#1]
Hi Julien,

I'm trying to use your script/module and running into a few issues:

[user@system ~]$ ./allocine.py  Vegas
Traceback (most recent call last):
  File "./allocine.py", line 102, in <module>
    results = allocine.search_movie(search)
  File "./allocine.py", line 90, in search_movie
    results = json.loads(result_json)
  File "/usr/lib64/python2.7/json/**init**.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

This is on RHEL7.2 with python 2.7.5.

Any ideas?

I'm mostly looking for a way to match movie posters from titles of movies on Allo Cine (in French).

Thanks,

Vincent

**Comment by JulienPalard** [comment]
Nice spot, looks like allocine closed the API I used : http://api.allocine.fr/xml/search.

If you find another API please just tell me I may update this project, but it's clearly unmaintained for now.

You may simply take a look at dbpedia ? I'm not aware if dbpedia expose multiple languages, if not, just get the box (on which dbpedia is based on) in french Wikipedia article like in https://fr.wikipedia.org/wiki/Las_Vegas_Parano which contains : 

```
Titre québécois   Peur et dégoût à Las Vegas
Titre original  Fear and Loathing in Las Vegas
Réalisation    Terry Gilliam
Scénario   Terry Gilliam
Tony Grisoni
Alex Cox
Tod Davies
Acteurs principaux  
Johnny Depp
Benicio del Toro
Sociétés de production    Rhino Films
Summit Entertainment
Pays d’origine    Drapeau des États-Unis États-Unis
Genre   Comédie dramatique
Durée  118 minutes
Sortie  1998
```

**Comment by ElCoyote27** [comment]
Hi Julien,
Merci du retour rapide. Je pense que Allocine a d'autres versions de l'API (on en trouve des traces sur github).. Je cherchais juste un moyen de trouver les affiches des films a partir du titre (en francais) pour pouvoir les telecharger.. Il va falloir que je me renseigne mais merci beaucoup encore une fois pour la reponse rapide.
A+
Vincent

**Comment by JulienPalard** [comment]
> Je cherchais juste un moyen de trouver les affiches des films a partir du titre (en francais) pour pouvoir les telecharger.

Wikipedia tout simplement ?

**Comment by JulienPalard** [comment]
I announced the project is dead / no longer working on the README file, thanks for reporting.

**Comment by JulienPalard** [comment]
(En passant si tu fais un truc en Python, on bosse sur la doc en Francais : http://www.afpy.org/doc/python/3.5/ et si tu as des questions n'hésite pas a nous rejoindre sur #python-fr sur irc.freenode.net)
